{% set data = load_setup_py_data() %}

package:
  name: conda-content-trust
  version: {{ data['version'] }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
    - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}

requirements:
  host:
    - python
    - pip
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - ruamel_yaml
  commands:
    - pytest -v tests
    - conda-content-trust --help

about:
  home: https://github.com/conda/conda-content-trust
  summary: Signing and verification tools for Conda"
  license: {{ data.get("license", "Unknown") }}
  license_file: LICENSE
